---
- name: Get join command
  command: kubeadm token create --print-join-command
  delegate_to: k8s-master
  run_once: yes
  register: join_cmd

- name: Join worker node to cluster
  command: "{{ join_cmd.stdout }} --cri-socket=unix:///var/run/crio/crio.sock --ignore-preflight-errors=all"

