- name: Initialize control plane
  command: >
    kubeadm init
    --apiserver-advertise-address=192.168.56.10
    --pod-network-cidr=192.168.0.0/16
    --cri-socket=unix:///var/run/crio/crio.sock
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy admin.conf to vagrant home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: '0600'

- name: Wait for API server to be reachable
  become_user: vagrant
  shell: kubectl get nodes
  register: kubectl_ready
  retries: 15
  delay: 10
  until: kubectl_ready.rc == 0

# - name: Install Calico
#   become_user: vagrant
#   shell: |
#     kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/calico.yaml

# Install Helm

- name: Install Helm (v3) if not present
  become: yes
  shell: |
    curl -fsSL https://get.helm.sh/helm-v3.16.2-linux-amd64.tar.gz -o /tmp/helm.tar.gz
    tar -C /tmp -zxf /tmp/helm.tar.gz
    mv /tmp/linux-amd64/helm /usr/local/bin/helm
    chmod +x /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm

# CILIUM through Helm

- name: Add Cilium Helm repo
  become_user: vagrant
  shell: |
    helm repo add cilium https://helm.cilium.io || true
    helm repo update
  environment:
    KUBECONFIG: /home/vagrant/.kube/config

# 1.18.4 - latest stable
- name: Install Cilium via Helm
  become_user: vagrant
  shell: |
    helm upgrade --install cilium cilium/cilium \
      --version 1.18.4 \
      --namespace kube-system \
      --create-namespace
  environment:
    KUBECONFIG: /home/vagrant/.kube/config

